# Generated by Django 3.1.7 on 2021-03-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='votes_to_skip_song',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
