# Generated by Django 3.1.7 on 2021-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, unique=True)),
                ('refresh_token', models.CharField(max_length=160)),
                ('access_token', models.CharField(max_length=160)),
                ('token_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_in', models.DateTimeField()),
            ],
            options={
                'db_table': 'spotify_token',
            },
        ),
    ]
